### ISSUE TITLE
Need a dummy user Id & Password so I can access application

### ISSUE THREAD

**Issue by Deepanwita** [tusksolutions/xmpp-chat-ios#4]
Hi,

"mobileservices/v1/store_message.php"
How can i replace this, bcoz i can't access this.

other this I'm not able to ping anyone.

NSMutableDictionary *dicToApi = [NSMutableDictionary dictionaryWithObjectsAndKeys:
                                     [NSString stringWithFormat:@"%@%@",URL_SCHEME,XAppDelegate.currentHost],@"baseUrl",
                                     @"mobileservices/v1/store_message.php",@"api",
                                     [TCUtility GetUUID],@"mid",
                                     nil];

**Comment by donaldking** [comment]
You don't need to use it. You can simply comment it out. Hope this is not too late? :)

**Comment by cobrasoftwares** [comment]
Hi
 we would like to use your coding for our project but we could not find the server side api code. the link uat.yookochat.com server is down. can i have the server side code or any help is appreciated.
